// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVubsS01ELhkEVFLtq69MH1P2xyMvQj6w',
    appId: '1:507039180720:web:aadc18bb65b03e9b909875',
    messagingSenderId: '507039180720',
    projectId: 'mylez-fintek-app',
    authDomain: 'mylez-fintek-app.firebaseapp.com',
    storageBucket: 'mylez-fintek-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAYPH2aOS02uyQuW0kvVQhSYWlNhyr7pk',
    appId: '1:507039180720:android:4b1b1c58c4596608909875',
    messagingSenderId: '507039180720',
    projectId: 'mylez-fintek-app',
    storageBucket: 'mylez-fintek-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFevuHw-7PNJ6lKSFm0s3D6MFVPxrV-80',
    appId: '1:507039180720:ios:e6deabbe013b7c9e909875',
    messagingSenderId: '507039180720',
    projectId: 'mylez-fintek-app',
    storageBucket: 'mylez-fintek-app.appspot.com',
    iosClientId: '507039180720-550l4j8f664u0v2jq1li57dvjophjrr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFevuHw-7PNJ6lKSFm0s3D6MFVPxrV-80',
    appId: '1:507039180720:ios:e6deabbe013b7c9e909875',
    messagingSenderId: '507039180720',
    projectId: 'mylez-fintek-app',
    storageBucket: 'mylez-fintek-app.appspot.com',
    iosClientId: '507039180720-550l4j8f664u0v2jq1li57dvjophjrr9.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintek',
  );
}
